language: R
cache: packages

r_packages:
  - devtools

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - richelbilderbeek/cobaltr

before_script:
  - Rscript -e 'devtools::install_github("richelbilderbeek/cobaltr")'
  - Rscript -e 'cobaltr::install_cobalt()'

script:
  # Do the actual build
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz
  # Break when style is incorrect
  - R CMD INSTALL *tar.gz
  - Rscript -e "lintr::expect_lint_free()"

after_success:
  # lintr-bot is mild
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - # No local files created
  - if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi;
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

